export default {
    GameLogo: require('./Images/GameLogo.png'),
    SpaceBackground1: require('./Images/SpaceBackground1.png'),
    SpaceBackground2: require('./Images/SpaceBackground2.png'),
    Meteor: require('./Images/meteor.png'),
    Earth: require('./Images/Earth.png'),
    Mars: require('./Images/Mars.png'),
    PlanetSheild: require("./Images/planetSheild.png"),
    BackButton: require("./Images/backButton.png"),
    EarthBackground: require("./Images/EarthBackground.jpg"),
    VenusBackground: require("./Images/VenusBackground.jpg"),
    MarsBackground: require("./Images/MarsBackground.jpg"),
    JupiterBackground: require("./Images/JupiterBackground.jpg"),
    BackButton2: require("./Images/backButton2.png"),
    Jupiter: require("./Images/Jupiter.png"),
    Venus: require("./Images/Venus.png"),
    ExplosionSprite: require("./Images/ExplosionSprite.png"),
}