export default {
    GameLogo: ('./Images/GameLogo.png'),
    SpaceBackground1: ('./Images/SpaceBackground1.png'),
    SpaceBackground2: ('./Images/SpaceBackground2.png'),
    Meteor: ('./Images/meteor.png'),
    Earth: ('./Images/Earth.png'),
    Mars: ('./Images/Mars.png'),
    PlanetSheild: ("./Images/planetSheild.png"),
    BackButton: ("./Images/backButton.png"),
    EarthBackground: ("./Images/EarthBackground.jpg"),
    VenusBackground: ("./Images/VenusBackground.jpg"),
    MarsBackground: ("./Images/MarsBackground.jpg"),
    JupiterBackground: ("./Images/JupiterBackground.jpg"),
    BackButton2: ("./Images/backButton2.png"),
    Jupiter: ("./Images/Jupiter.png"),
    Venus: ("./Images/Venus.png"),
    ExplosionSprite: ("./Images/ExplosionSprite.png"),
    BlackHole: ("./Images/BlackHole.png"),
}